### ISSUE TITLE
Support empty ModOps + simplify True/False sections

### ISSUE THREAD

**Issue by jakobharder** [anno-mods/iModYourAnno#117]
I currently have the following.

```
  <!-- # Shift+V fix -->
  <ModOp Type="replace" GUID="1010325" Path="/Values/QuestObject" ModOpID="ShiftVFix" Skip="1" />
  <ModOp Type="replace" GUID="1010291" Path="/Values/QuestObject" ModOpID="ShiftVFix" Skip="1" />
  <ModOp Type="replace" GUID="1010295" Path="/Values/QuestObject" ModOpID="ShiftVFix" Skip="1" />
```

```
  <!-- # Enable Tweaks -->
  <ImyaExpose Path=".." ModOpID="ShiftVFix" ExposeID="Shift+V Fix"
    Description="Removes QuestObject from buildings to improve Shift+V behavior." Kind="Toggle">
    <TrueValue>
      <QuestObject />
    </TrueValue>
    <FalseValue />
  </ImyaExpose>
  <Include File="../assets.imyatweak.xml" />
```

```
<ModOps>
  <ModOp Path="/Values/QuestObject" GUID="1010325" Type="replace" />
  <ModOp Path="/Values/QuestObject" GUID="1010291" Type="replace" />
  <ModOp Path="/Values/QuestObject" GUID="1010295" Type="replace" />
</ModOps>
```

1. True works, false doesn't. It doesn't work well with empty ModOps yet I think.
2. How about renaming `ExposeID` to `Name`? ID kinda suggests it's linked to something else and doesn't allow spaces etc.
3. How about having a simple Expose that can just copy the whole ModOp on True or False and skips it on the other? I have to place the content of the ModOp in 3 locations now (ModOp, Expose and tweak.xml).
4. At least in the toggle use case we should be able to live without writing the original ModOp completely.

**Comment by taubenangriff** [comment]
1. Well, I think this case might be pretty specific. any empty add is okay, but for some reason replace isn't.... Well nothing you can't solve, should be good to just replace an empty replace modop with remove while generating

2. The reason I chose ID is that it emphazises uniqueness stronger, but I am open for discussion here. 

3. I already thought about it as the duplication leaves you in a three-state system with untweaked, true or false. Honestly, stupid me, why do I even think of doing it this way. In general, just using the modop content selected with the expose path instead of defining a truevalue should also do the trick.
